version: '3.1'

services:
  history-editor:
    container_name: history-editor
    image: history-editor
    ports:
      - '0.0.0.0:8081:3000'
    volumes:
      - ./log:/app/log
      - ./db:/app/db
      - ./config/master.key:/app/config/master.key
      - development.sqlite3:/app/db/development.sqlite3
      - production.sqlite3:/app/db/production.sqlite3
    environment:
      - RAILS_ENV=production
      # These override config/puma.rb, but are defaults anyway.
      - WEB_CONCURRENCY=2
      - RAILS_MAX_THREADS=5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/history-editor/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s