---
Student Life: https://media.archives.albany.edu/ua390/375a97172e5a3a881fec0307f954353f/thumbnail.jpg
Presidents: https://media.archives.albany.edu/ua390/1dd4c014e556586104948edb563d8198/thumbnail.jpg
Administration: https://media.archives.albany.edu/ua390/28a5c95d265ffd6a5320f88233764677/thumbnail.jpg
Alumni: https://media.archives.albany.edu/ua390/625a703e0bba16056651e7ecd54cdccf/thumbnail.jpg
Centers & Institutes: https://media.archives.albany.edu/ua395/2a497fd0181f923dabf6cdd9ade38758/thumbnail.jpg
Academic Colleges, Schools & Departments: https://media.archives.albany.edu/ua390/55504ff48b16497bb3da239a94830a6c/thumbnail.jpg
University Names: https://media.archives.albany.edu/ua395/732bfc1bdae253d5bf33dbdc6ef6cd9e/thumbnail.jpg
Enrollment: https://media.archives.albany.edu/ua390/e9a9193ae7bd3f85a2614fbf5c9e244b/thumbnail.jpg
Academic Programs: https://media.archives.albany.edu/ua390/bb74e6faebe7557a56bd644d1800ba96/thumbnail.jpg
Notable Students: https://media.archives.albany.edu/ua390/6ad02e0cbfd11d52a041a75bfead2d56/thumbnail.jpg
Buildings & Construction: https://media.archives.albany.edu/ua950.005/aab39f18a5f5beff8dccbe098d428c83/thumbnail.jpg
Milne School: https://media.archives.albany.edu/ua950.008/d36ff4b6f5c5e75e7279f4b758e4cc11/thumbnail.jpg
Campus Activism: https://media.archives.albany.edu/ua950.008/a1f59876191c00f3506bb4a09a29de8e/thumbnail.jpg
Educational Opportunity Program: https://media.archives.albany.edu/ua390/cbddee1f55399cc31f06dd0d8ebaef50/thumbnail.jpg
